set -g window-status-style 'fg=#969696,bg=#2d2d2d'
set -g window-status-current-style 'fg=#1e1e1e,bg=#e7e7e7,bold'
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W '
set -g window-status-separator ' '
