# unbind C-b
# set-option -g prefix C-Space
# bind C-Space send-prefix

set-window-option -g mode-keys vi
set-option -g default-shell /bin/zsh
set -g extended-keys on

source-file ~/.config/tmux/tmux-style.conf

# Reload tmux config
# bind C-R source-file ~/.config/tmux/tmux.conf
bind R source-file ~/.config/tmux/tmux.conf

# Switch windows with Alt+up/down
bind -n M-Up next-window
bind -n M-Down previous-window
# Move windows with Alt+Ctrl+up/down
bind -n M-C-Up swap-window -t +1\; select-window -t +1
bind -n M-C-Down swap-window -t -1\; select-window -t -1

# Split windows with leader |/-
bind | split-window -h
bind - split-window -v

# Switch panes with Alt+left/right
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R

# Plugins
set -g @plugin ' \
	tmux-plugins/tpm \
	tmux-plugins/tmux-resurrect
'

# Tmux Plugin Manager INIT
run '~/.config/tmux/plugins/tpm/tpm'
