#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
# PS1='[\u@\h \W]\$ '

source '/home/ctn/.config/bash/bash_aliases'

eval "$(zoxide init zsh)"

# opencode
export PATH=/home/ctn/.opencode/bin:$PATH

# # pnpm
# export PNPM_HOME="/home/ctn/.local/share/pnpm"
# case ":$PATH:" in
#   *":$PNPM_HOME:"*) ;;
#   *) export PATH="$PNPM_HOME:$PATH" ;;
# esac
# # pnpm end
