#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
# PS1='[\u@\h \W]\$ '

source '.config/bash/bash_aliases'
source '.config/bash/startup.bash'

# opencode
export PATH=.opencode/bin:$PATH

